import { Button } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import HeroBanner from '../components/HeroBanner'
import Navbar from '../components/Navbar'
import Products from '../components/Products'
import { client } from '../lib/client'
import styles from '../styles/Home.module.css'

const Home: NextPage = ({ products, banners }: any) => {
  // console.log(products,'products')
  // console.log(banners,'banners')

  return (
    <div >
      <Head>
        <title>Phanox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroBanner data={banners[0]} />
      <Products products={products} />
      <Footer data={banners[0]} />
    </div>
  )
}







export const getServerSideProps = async () => {
  const query = '*[_type == "product"]'
  const products = await client.fetch(query)
  const banner_query = '*[_type == "banner"]'
  const banners = await client.fetch(banner_query)

  return {
    props: { products, banners }
  }
}

export default Home
